src/Presentation/SmartStore.Web/Models/Customer/AccountActivationModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class AccountActivationModel : ModelBase
    {
        public string Result { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/BackInStockSubscriptionModel.cs
using SmartStore.Services.Localization;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class BackInStockSubscriptionModel : EntityModelBase
    {
        public int ProductId { get; set; }
        public LocalizedValue<string> ProductName { get; set; }
        public string SeName { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using FluentValidation;
using FluentValidation.Attributes;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Localization;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
	[Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : ModelBase
    {
        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [SmartResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }
    }

    public class ChangePasswordValidator : AbstractValidator<ChangePasswordModel>
    {
        public ChangePasswordValidator(Localizer T, CustomerSettings customerSettings)
        {
            RuleFor(x => x.OldPassword).NotEmpty();
            RuleFor(x => x.NewPassword).NotEmpty();
            RuleFor(x => x.ConfirmNewPassword).NotEmpty();
            RuleFor(x => x.NewPassword).Length(customerSettings.PasswordMinLength, 999);

            RuleFor(x => x.ConfirmNewPassword).Equal(x => x.NewPassword).WithMessage(T("Account.ChangePassword.Fields.NewPassword.EnteredPasswordsDoNotMatch"));
        }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressEditModel.cs
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressEditModel : ModelBase
    {
        public CustomerAddressEditModel()
        {
            this.Address = new AddressModel();
        }
        public AddressModel Address { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAddressListModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Models.Common;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAddressListModel : ModelBase
    {
        public CustomerAddressListModel()
        {
            Addresses = new List<AddressModel>();
        }

        public IList<AddressModel> Addresses { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerAvatarModel.cs
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerAvatarModel : ModelBase
    {
        public bool Large { get; set; }
        public string PictureUrl { get; set; }
        public string LinkUrl { get; set; }
        public string AvatarColor { get; set; }
        public char AvatarLetter { get; set; }
        public string UserName { get; set; }
    }

    public partial class CustomerAvatarEditModel : ModelBase
    {
		public string MaxFileSize { get; set; }
        public CustomerAvatarModel Avatar { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerBackInStockSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerBackInStockSubscriptionsModel : PagedListBase
    {
        public CustomerBackInStockSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.Subscriptions = new List<BackInStockSubscriptionModel>();
        }

        public IList<BackInStockSubscriptionModel> Subscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerDownloadableProductsModel.cs
using System;
using System.Collections.Generic;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Services.Localization;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerDownloadableProductsModel : ModelBase
    {
        public CustomerDownloadableProductsModel()
        {
            Items = new List<DownloadableProductsModel>();
        }

        public IList<DownloadableProductsModel> Items { get; set; }

        #region Nested classes

        public partial class DownloadableProductsModel : ModelBase
        {
            public DownloadableProductsModel()
            {
                DownloadVersions = new List<DownloadVersion>();
            }

            public Guid OrderItemGuid { get; set; }

            public int OrderId { get; set; }

            public int ProductId { get; set; }
            public LocalizedValue<string> ProductName { get; set; }
            public string ProductSeName { get; set; }
			public string ProductUrl { get; set; }
            public string ProductAttributes { get; set; }

            public int LicenseId { get; set; }
            public bool IsDownloadAllowed { get; set; }

            public DateTime CreatedOn { get; set; }

            public List<DownloadVersion> DownloadVersions { get; set; }
        }

        #endregion
    }

    public partial class UserAgreementModel : ModelBase
    {
        public Guid OrderItemGuid { get; set; }
        public string UserAgreementText { get; set; }
        public string FileVersion { get; set; }
    }

    public class DownloadVersion
    {
        public int DownloadId { get; set; }
        public string FileName { get; set; }
        public Guid DownloadGuid { get; set; }
        public string FileVersion { get; set; }
        public string Changelog { get; set; }
    }

}

src/Presentation/SmartStore.Web/Models/Customer/CustomerForumSubscriptionsModel.cs
using System.Collections.Generic;
using SmartStore.Core;

namespace SmartStore.Web.Models.Customer
{
    public partial class CustomerForumSubscriptionsModel : PagedListBase
    {
        public CustomerForumSubscriptionsModel(IPageable pageable) : base(pageable)
        {
            this.ForumSubscriptions = new List<ForumSubscriptionModel>();
        }

        public IList<ForumSubscriptionModel> ForumSubscriptions { get; set; }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/CustomerInfoModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation;
using FluentValidation.Attributes;
using SmartStore.Core.Domain.Customers;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Modelling;
using SmartStore.Web.Framework.Security;

namespace SmartStore.Web.Models.Customer
{
	[Validator(typeof(CustomerInfoValidator))]
    public partial class CustomerInfoModel : ModelBase
    {
        public CustomerInfoModel()
        {
            this.AvailableTimeZones = new List<SelectListItem>();
            this.AvailableCountries = new List<SelectListItem>();
            this.AvailableStates = new List<SelectListItem>();
            this.AssociatedExternalAuthRecords = new List<AssociatedExternalAuthModel>();
        }

        [SmartResourceDisplayName("Account.Fields.Email")]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }

        [SmartResourceDisplayName("Account.Fields.CustomerNumber")]
        public string CustomerNumber { get; set; }
        public bool CustomerNumberEnabled { get; set; }
        public bool DisplayCustomerNumber { get; set; }

        public bool CheckUsernameAvailabilityEnabled { get; set; }
        public bool AllowUsersToChangeUsernames { get; set; }
        public bool UsernamesEnabled { get; set; }

        [SmartResourceDisplayName("Account.Fields.Username")]
        public string Username { get; set; }

        //form fields & properties
        public bool GenderEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Gender")]
        public string Gender { get; set; }

        public bool TitleEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Title")]
        public string Title { get; set; }
        
        [SmartResourceDisplayName("Account.Fields.FirstName")]
        public string FirstName { get; set; }

        [SmartResourceDisplayName("Account.Fields.LastName")]
        public string LastName { get; set; }


        public bool DateOfBirthEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthDay { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthMonth { get; set; }
        [SmartResourceDisplayName("Account.Fields.DateOfBirth")]
        public int? DateOfBirthYear { get; set; }

        public bool CompanyEnabled { get; set; }
        public bool CompanyRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Company")]
        public string Company { get; set; }

        public bool StreetAddressEnabled { get; set; }
        public bool StreetAddressRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.StreetAddress")]
        public string StreetAddress { get; set; }

        public bool StreetAddress2Enabled { get; set; }
        public bool StreetAddress2Required { get; set; }
        [SmartResourceDisplayName("Account.Fields.StreetAddress2")]
        public string StreetAddress2 { get; set; }

        public bool ZipPostalCodeEnabled { get; set; }
        public bool ZipPostalCodeRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.ZipPostalCode")]
        public string ZipPostalCode { get; set; }

        public bool CityEnabled { get; set; }
        public bool CityRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.City")]
        public string City { get; set; }

        public bool CountryEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Country")]
        public int CountryId { get; set; }
        public IList<SelectListItem> AvailableCountries { get; set; }

        public bool StateProvinceEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.StateProvince")]
        public int StateProvinceId { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }

        public bool PhoneEnabled { get; set; }
        public bool PhoneRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Phone")]
		[DataType(DataType.PhoneNumber)]
		public string Phone { get; set; }

        public bool FaxEnabled { get; set; }
        public bool FaxRequired { get; set; }
        [SmartResourceDisplayName("Account.Fields.Fax")]
		[DataType(DataType.PhoneNumber)]
		public string Fax { get; set; }

        public bool NewsletterEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Newsletter")]
        public bool Newsletter { get; set; }

        //preferences
        public bool SignatureEnabled { get; set; }
        [SmartResourceDisplayName("Account.Fields.Signature")]
        [SanitizeHtml]
        public string Signature { get; set; }

        //time zone
        [SmartResourceDisplayName("Account.Fields.TimeZone")]
        public string TimeZoneId { get; set; }
        public bool AllowCustomersToSetTimeZone { get; set; }
        public IList<SelectListItem> AvailableTimeZones { get; set; }

        //EU VAT
        [SmartResourceDisplayName("Account.Fields.VatNumber")]
        public string VatNumber { get; set; }
        public string VatNumberStatusNote { get; set; }
        public bool DisplayVatNumber { get; set; }

        //external authentication
        [SmartResourceDisplayName("Account.AssociatedExternalAuth")]
        public IList<AssociatedExternalAuthModel> AssociatedExternalAuthRecords { get; set; }

        #region Nested classes

        public partial class AssociatedExternalAuthModel : EntityModelBase
        {
            public string Email { get; set; }
            public string ExternalIdentifier { get; set; }
            public string AuthMethodName { get; set; }
        }
        
        #endregion
    }

    public class CustomerInfoValidator : AbstractValidator<CustomerInfoModel>
    {
        public CustomerInfoValidator(CustomerSettings customerSettings)
        {
            RuleFor(x => x.Email).NotEmpty();
            RuleFor(x => x.Email).EmailAddress();

            //form fields
            if (customerSettings.FirstNameRequired)
            {
                RuleFor(x => x.FirstName).NotEmpty();
            }
            if (customerSettings.LastNameRequired)
            {
                RuleFor(x => x.LastName).NotEmpty();
            }
            if (customerSettings.CompanyRequired && customerSettings.CompanyEnabled)
            {
                RuleFor(x => x.Company).NotEmpty();
            }
            if (customerSettings.StreetAddressRequired && customerSettings.StreetAddressEnabled)
            {
                RuleFor(x => x.StreetAddress).NotEmpty();
            }
            if (customerSettings.StreetAddress2Required && customerSettings.StreetAddress2Enabled)
            {
                RuleFor(x => x.StreetAddress2).NotEmpty();
            }
            if (customerSettings.ZipPostalCodeRequired && customerSettings.ZipPostalCodeEnabled)
            {
                RuleFor(x => x.ZipPostalCode).NotEmpty();
            }
            if (customerSettings.CityRequired && customerSettings.CityEnabled)
            {
                RuleFor(x => x.City).NotEmpty();
            }
            if (customerSettings.PhoneRequired && customerSettings.PhoneEnabled)
            {
                RuleFor(x => x.Phone).NotEmpty();
            }
            if (customerSettings.FaxRequired && customerSettings.FaxEnabled)
            {
                RuleFor(x => x.Fax).NotEmpty();
            }
        }
    }
}

src/Presentation/SmartStore.Web/Models/Customer/ExternalAuthenticationMethodModel.cs
using System.Web.Routing;
using SmartStore.Web.Framework.Modelling;

namespace SmartStore.Web.Models.Customer
{
    public partial class ExternalAuthenticationMethodModel : ModelBase
    {
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public RouteValueDictionary RouteValues { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using SmartStore.Core;
using SmartStore.Core.Caching;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Web.Infrastructure.Cache;
using SmartStore.Web.Framework.Controllers;

namespace SmartStore.Web.Controllers
{
    public partial class CountryController : PublicControllerBase
    {
        #region Fields

        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly ICacheManager _cacheManager;

        #endregion

        #region Constructors

        public CountryController(ICountryService countryService,
            IStateProvinceService stateProvinceService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            ICacheManager cacheManager)
        {
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._cacheManager = cacheManager;
        }

        #endregion

        #region States / provinces

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetAllStates()
        {

            var states = _stateProvinceService.GetAllStateProvinces().ToList();
            var result = (from s in states
                          select new { id = s.Id, name = s.GetLocalized(x => x.Name).Value })
                          .ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// It will fetch states based on country id. If the country id will not have any state 
        /// mapped to it, the method will will reture"Other as a value"
        /// </summary>
        /// <param name="countryId"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetStatesByCountryId(int countryId)
        {
            var states = _stateProvinceService.GetStateProvincesByCountryId(countryId).ToList();

            var result = (from s in states
                          select new { id = s.Id, name = s.Name })
                          .ToList();

            if (result.Count == 0)
            {
                result.Insert(0, new { id = 0, name = _localizationService.GetResource("Address.Other") });
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Views/Customer/AccountActivation.cshtml
@model AccountActivationModel
@using SmartStore.Web.Models.Customer;
@{
    Layout = "_Layout";

    Html.AddTitleParts(T("PageTitle.AccountActivation").Text);
}

<div class="page account-activation-page">
    <div class="page-title">
        <h1>@T("Account.AccountActivation")</h1>
    </div>
    <div class="page-body">
        <strong>@Model.Result</strong>
    </div>
</div>

src/Presentation/SmartStore.Web/Views/Customer/Info.cshtml
@model CustomerInfoModel
@using SmartStore.Web.Models.Customer;
@{
    Html.AddTitleParts(T("PageTitle.Account").Text);

    Layout = "_MyAccount";
    ViewBag.PageClassToken = "info";
    ViewBag.PageTitle = T("Account.CustomerInfo").Text;
}
@using (Html.BeginForm("Info", "Customer", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
    }

    <fieldset class="content-group">
        <legend><span>@T("Account.YourPersonalDetails")</span></legend>
        @if (Model.GenderEnabled)
        {
            <div class="form-group row">
                <label class="col-lg-3 col-form-label">@T("Account.Fields.Gender")</label>
                <div class="col-lg-9 form-inline">
                    <div class="form-check form-check-inline">
                        @Html.RadioButton("Gender", "M", (Model.Gender == "M"), new { @class = "form-check-input", id = "gender-male" })
                        <label class="form-check-label" for="gender-male">@T("Account.Fields.Gender.Male")</label>
                    </div>
                    <div class="form-check form-check-inline">
                        @Html.RadioButton("Gender", "F", (Model.Gender == "F"), new { @class = "form-check-input", id = "gender-female" })
                        <label class="form-check-label" for="gender-female">@T("Account.Fields.Gender.Female")</label>
                    </div>
                </div>
            </div>
        }
        @if (Model.TitleEnabled)
        {
            @Html.ControlGroupFor(model => model.Title, required: false, breakpoint: "lg")
        }
        @Html.ControlGroupFor(model => model.FirstName, required: true, breakpoint: "lg")
        @Html.ControlGroupFor(model => model.LastName, required: true, breakpoint: "lg")
        @if (Model.DateOfBirthEnabled)
        {
            <div class="form-group row">
                <label class="col-lg-3 col-form-label" for="DateOfBirthDay">@T("Account.Fields.DateOfBirth")</label>
                <div class="col-lg-9">
                    @Html.DatePickerDropDowns(Html.FieldNameFor(x => x.DateOfBirthDay),
                            Html.FieldNameFor(x => x.DateOfBirthMonth),
                            Html.FieldNameFor(x => x.DateOfBirthYear),
                            DateTime.Now.Year - 110,
                            DateTime.Now.Year,
                            Model.DateOfBirthDay,
                            Model.DateOfBirthMonth,
                            Model.DateOfBirthYear)
                    @Html.ValidationMessageFor(model => model.DateOfBirthDay)
                    @Html.ValidationMessageFor(model => model.DateOfBirthMonth)
                    @Html.ValidationMessageFor(model => model.DateOfBirthYear)
                </div>
            </div>
        }
        @Html.ControlGroupFor(model => model.Email, required: true, breakpoint: "lg")
        @if (Model.UsernamesEnabled)
        {
            <div class="form-group row">
                @Html.LabelFor(model => model.Username, new { @class = "col-lg-3 col-form-label required", @for = "Username" })
                @if (Model.AllowUsersToChangeUsernames)
                {
                    <div class="col-lg-9">
                        @if (Model.CheckUsernameAvailabilityEnabled)
                        {
                            <div class="input-group">
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
                                @{ Html.RenderPartial("_CheckUsernameAvailability"); }
                            </div>
                        }
                        else
                        {
                            @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
                        }
                        @Html.ValidationMessageFor(model => model.Username)
                    </div>
                }
                else
                {
                    <div class="col-lg-9">
                        <div class="form-control-plaintext">@Model.Username</div>
                    </div>
                }
            </div>
        }
        @if (Model.DisplayCustomerNumber)
        {
            var customerNumberAttributes = !Model.CustomerNumberEnabled ? (object)(new { @class = "form-control", @readonly = "true" }) : (object)(new { @class = "form-control" });
            <div class="form-group row">
                @Html.LabelFor(model => model.CustomerNumber, new { @class = "col-lg-3 col-form-label", @for = "CustomerNumber" })
                <div class="col-lg-9">
                    @Html.TextBoxFor(model => model.CustomerNumber, customerNumberAttributes)
                </div>
            </div>
        }
    </fieldset>

    if (Model.AssociatedExternalAuthRecords.Count > 0)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.AssociatedExternalAuth")</span></legend>
            <div class="table-responsive">
                <table class="table table-hover border-top-0">
                    <thead>
                        <tr>
                            <th class="border-top-0">
                                @T("Account.AssociatedExternalAuth.AuthMethodName")
                            </th>
                            <th class="border-top-0">
                                @T("Account.AssociatedExternalAuth.Email")
                            </th>
                            <th class="border-top-0">
                                @T("Account.AssociatedExternalAuth.ExternalIdentifier")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.AssociatedExternalAuthRecords)
                        {
                            <tr>
                                <td>
                                    @item.AuthMethodName
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>
                                    @item.ExternalIdentifier
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </fieldset>
    }

    if (Model.CompanyEnabled || Model.DisplayVatNumber)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.CompanyDetails")</span></legend>
            @if (Model.CompanyEnabled)
            {
                @Html.ControlGroupFor(model => model.Company, required: Model.CompanyRequired, breakpoint: "lg")
            }
            @if (Model.DisplayVatNumber)
            {
                <div class="form-group row">
                    @Html.LabelFor(model => model.VatNumber, new { @class = "col-lg-3 col-form-label", @for = "VatNumber" })
                    <div class="col-lg-9">
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.VatNumber, new { @class = "form-control", placeholder = T("Common.Optional") })
                            <div class="input-group-append"><span class="input-group-text">@Model.VatNumberStatusNote</span></div>
                        </div>
                        <div class="form-text text-muted vat-note">@T("Account.Fields.VatNumber.Note")</div>
                    </div>
                </div>
            }
        </fieldset>
    }

    if (Model.StreetAddressEnabled || Model.StreetAddress2Enabled || Model.ZipPostalCodeEnabled || Model.CityEnabled || Model.CountryEnabled)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.YourAddress")</span></legend>
            @if (Model.StreetAddressEnabled)
            {
                @Html.ControlGroupFor(model => model.StreetAddress, required: Model.StreetAddressRequired, breakpoint: "lg")
            }
            @if (Model.StreetAddress2Enabled)
            {
                @Html.ControlGroupFor(model => model.StreetAddress2, required: Model.StreetAddress2Required, breakpoint: "lg")
            }
            @if (Model.ZipPostalCodeEnabled)
            {
                @Html.ControlGroupFor(model => model.ZipPostalCode, required: Model.ZipPostalCodeRequired, breakpoint: "lg")
            }
            @if (Model.CityEnabled)
            {
                @Html.ControlGroupFor(model => model.City, required: Model.CityRequired, breakpoint: "lg")
            }
            @if (Model.CountryEnabled)
            {
                <div class="form-group row">
                    @Html.LabelFor(model => model.CountryId, new { @class = "col-lg-3 col-form-label", @for = "CountryId" })
                    <div class="col-lg-9">
                        @Html.DropDownList("CountryId", Model.AvailableCountries,
                            new { @class = "form-control country-input country-selector",
                                data_region_control_selector = "#StateProvinceId",
                                data_states_ajax_url = Url.Action("GetStatesByCountryId", "Country")
                            })
                    </div>
                </div>
            }
            @if (Model.CountryEnabled && Model.StateProvinceEnabled)
            {
                <div class="form-group row">
                    @Html.LabelFor(model => model.StateProvinceId, new { @class = "col-lg-3 col-form-label", @for = "StateProvinceId" })
                    <div class="col-lg-9">
                        @Html.DropDownList("StateProvinceId", Model.AvailableStates, new { @class = "form-control" })
                    </div>
                </div>
            }
        </fieldset>
    }

    if (Model.PhoneEnabled || Model.FaxEnabled)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.YourContactInformation")</span></legend>
            @if (Model.PhoneEnabled)
            {
                @Html.ControlGroupFor(model => model.Phone, required: Model.PhoneRequired, breakpoint: "lg")
            }
            @if (Model.FaxEnabled)
            {
                @Html.ControlGroupFor(model => model.Fax, required: Model.FaxRequired, breakpoint: "lg")
            }
        </fieldset>
    }

    if (Model.NewsletterEnabled)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.Options")</span></legend>
            <div class="form-group row">
                <div class="col">
                    <div class="form-check">
                        @Html.EditorFor(model => model.Newsletter, new { @class = "form-check-input" })
                        <label class="form-check-label" for="Newsletter">
                            @T("Account.Fields.Newsletter", Url.Topic("PrivacyInfo"))
                        </label>
                    </div>
                </div>
            </div>
        </fieldset>
    }

    if (Model.AllowCustomersToSetTimeZone || Model.SignatureEnabled)
    {
        <fieldset class="content-group">
            <legend><span>@T("Account.Preferences")</span></legend>
            @if (Model.AllowCustomersToSetTimeZone)
            {
                <div class="form-group row">
                    @Html.LabelFor(model => model.TimeZoneId, new { @class = "col-lg-3 col-form-label", @for = "TimeZoneId" })
                    <div class="col-lg-9">
                        @Html.DropDownList("TimeZoneId", Model.AvailableTimeZones, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TimeZoneId)
                    </div>
                </div>
            }
            @if (Model.SignatureEnabled)
            {
                <div class="form-group row">
                    @Html.LabelFor(model => model.Signature, new { @class = "col-lg-3 col-form-label", @for = "Signature" })
                    <div class="col-lg-9">
                        @Html.TextAreaFor(model => model.Signature, new { placeholder = T("Common.Optional"), @class = "form-control", rows = "3" })
                    </div>
                </div>
            }
        </fieldset>
    }

    <div class="form-group row">
        <div class="col-12 text-muted">
            @T("Common.FormFields.Required.Hint")
        </div>
    </div>

    <div class="form-group row">
        <div class="col">
            <button type="submit" name="save-info-button" class="btn btn-primary btn-lg save-customer-info-button">
                <i class="fa fa-check"></i>
                <span>@T("Common.Save")</span>
            </button>
        </div>
    </div>
}